// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POAPI.Data;

#nullable disable

namespace POAPI.Migrations
{
    [DbContext(typeof(PoDbContext))]
    partial class PoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("POAPI.Aggregates.PO.PurchaseOrder", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PurchaseQuoteId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PurchaseRequestId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("POAPI.Aggregates.PQ.PurchaseQuote", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PurchaseRequestId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PurchaseQuotes");
                });

            modelBuilder.Entity("POAPI.Aggregates.PR.PurchaseRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PurchaseRequests");
                });

            modelBuilder.Entity("POAPI.Aggregates.PO.PurchaseOrder", b =>
                {
                    b.OwnsOne("POAPI.Aggregates.PO.PurchaseOrderStatus", "Status", b1 =>
                        {
                            b1.Property<string>("PurchaseOrderId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("Status_Id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Status_Name");

                            b1.HasKey("PurchaseOrderId");

                            b1.ToTable("PurchaseOrders");

                            b1.WithOwner()
                                .HasForeignKey("PurchaseOrderId");
                        });

                    b.Navigation("Status")
                        .IsRequired();
                });

            modelBuilder.Entity("POAPI.Aggregates.PQ.PurchaseQuote", b =>
                {
                    b.OwnsOne("POAPI.Shared.Money", "OfferAmount", b1 =>
                        {
                            b1.Property<string>("PurchaseQuoteId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Offer_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Offer_Currency");

                            b1.HasKey("PurchaseQuoteId");

                            b1.ToTable("PurchaseQuotes");

                            b1.WithOwner()
                                .HasForeignKey("PurchaseQuoteId");
                        });

                    b.OwnsOne("POAPI.Aggregates.PQ.PurchaseQuoteStatus", "Status", b1 =>
                        {
                            b1.Property<string>("PurchaseQuoteId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("Status_Id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Status_Name");

                            b1.HasKey("PurchaseQuoteId");

                            b1.ToTable("PurchaseQuotes");

                            b1.WithOwner()
                                .HasForeignKey("PurchaseQuoteId");
                        });

                    b.Navigation("OfferAmount")
                        .IsRequired();

                    b.Navigation("Status")
                        .IsRequired();
                });

            modelBuilder.Entity("POAPI.Aggregates.PR.PurchaseRequest", b =>
                {
                    b.OwnsOne("POAPI.Shared.Money", "Budget", b1 =>
                        {
                            b1.Property<string>("PurchaseRequestId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Budget_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Budget_Currency");

                            b1.HasKey("PurchaseRequestId");

                            b1.ToTable("PurchaseRequests");

                            b1.WithOwner()
                                .HasForeignKey("PurchaseRequestId");
                        });

                    b.OwnsOne("POAPI.Aggregates.PR.PurchaseRequestStatus", "Status", b1 =>
                        {
                            b1.Property<string>("PurchaseRequestId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("Status_Id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Status_Name");

                            b1.HasKey("PurchaseRequestId");

                            b1.ToTable("PurchaseRequests");

                            b1.WithOwner()
                                .HasForeignKey("PurchaseRequestId");
                        });

                    b.Navigation("Budget")
                        .IsRequired();

                    b.Navigation("Status")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
